version: '2'
services:
  web:
    build: .
    environment:
      DROPBOX_CLIENT_ID: "${DROPBOX_CLIENT_ID}"
      DROPBOX_CLIENT_SECRET: "${DROPBOX_CLIENT_SECRET}"
      DROPBOX_REDIRECT_URI: "${DROPBOX_REDIRECT_URI}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
    ports:
      - "3000:80"
