version: '2'
services:
  postgres:
    image: postgres:9.5
    environment:
      POSTGRES_PASSWORD: orgnotes
      POSTGRES_USER: orgnotes
      POSTGRES_DB: orgnotes
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
