version: '2'
services:
  web:
    build: .
    environment:
      DROPBOX_CLIENT_ID: YOUR_DROPBOX_CLIENT_ID
      DROPBOX_CLIENT_SECRET: YOUR_DROPBOX_CLIENT_SECRET
      DROPBOX_REDIRECT_URI: YOUR_DROPBOX_REDIRECT_URI
      SECRET_KEY_BASE: YOUR_SECRET_KEY_BASE
    ports:
      - "3000:80"
