default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

docker_local: &docker_local
  <<: *default
  host: localhost
  user: orgnotes
  password: orgnotes

development:
  <<: *docker_local
  database: orgnotes_dev

test:
  <<: *docker_local
  database: orgnotes_test

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: <%= ENV['DATABASE_HOST'] %>
  user: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
